# Generated by Django 4.0 on 2022-04-18 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file_upload',
            field=models.FileField(null=True, upload_to='posts', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv', 'png', 'jpg'])]),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
