# Generated by Django 4.0 on 2022-04-18 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_file_upload_post_post_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='post',
            new_name='post_liked',
        ),
        migrations.AddField(
            model_name='post',
            name='user_liked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.likes'),
        ),
    ]
