# Generated by Django 4.0 on 2022-04-18 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_post_likes_post_liked_post_user_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_liked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.likes'),
        ),
    ]
