# Generated by Django 4.0 on 2022-04-18 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_user_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='user_liked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.commentlikes'),
        ),
    ]
