# Generated by Django 4.0 on 2022-05-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='story_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
