# Generated by Django 4.0 on 2022-05-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_story_story_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='story_length_custom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_length',
            field=models.IntegerField(choices=[(5, '5'), (10, '10'), (15, '15'), (20, ' 20'), ('custom', 'custom')], null=True),
        ),
    ]
