# Generated by Django 4.0 on 2022-10-26 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_remove_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='likes',
        ),
    ]
