# Generated by Django 4.0 on 2022-10-26 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_is_active_profile_last_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='total_followers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total_following',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total_posts',
        ),
    ]
