# Generated by Django 4.0 on 2022-05-07 05:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainBubble',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=500, null=True)),
                ('in_chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.chat')),
            ],
        ),
        migrations.CreateModel(
            name='OtherBubble',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=500, null=True)),
                ('in_chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.chat')),
            ],
        ),
        migrations.DeleteModel(
            name='Bubble',
        ),
        migrations.AddField(
            model_name='chat',
            name='main_user_bubble',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chats.mainbubble'),
        ),
        migrations.AddField(
            model_name='chat',
            name='other_user_bubble',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chats.otherbubble'),
        ),
    ]
