# Generated by Django 4.0 on 2022-05-07 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_profile_pic'),
        ('chats', '0002_mainbubble_otherbubble_delete_bubble_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='main_user_bubble',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='other_user_bubble',
        ),
        migrations.AddField(
            model_name='chat',
            name='other_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='mainbubble',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='otherbubble',
            name='other',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
