# Generated by Django 4.0 on 2022-05-07 14:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_chat_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentActiveChat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active_chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.chat')),
            ],
        ),
    ]
