# Generated by Django 4.0 on 2022-05-07 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_currentactivechat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrentActiveChat',
        ),
    ]
